# Generated by Django 6.0.3 on 2026-03-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vip_level',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'VIP 1'), (2, 'VIP 2'), (3, 'VIP 3'), (4, 'VIP 4'), (5, 'VIP 5')], default=1),
        ),
    ]
