# Generated by Django 6.0.3 on 2026-03-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_profile_vip_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit_points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vip_level',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'VIP 1'), (2, 'VIP 2'), (3, 'VIP 3'), (4, 'VIP 4'), (5, 'VIP 5'), (6, 'VIP 6')], default=1),
        ),
    ]
