# Generated by Django 6.0.3 on 2026-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_profile_credit_points_alter_profile_vip_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='withdrawal_method',
            field=models.CharField(blank=True, help_text='e.g., Bank Card, USDT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vip_level',
            field=models.IntegerField(choices=[(0, 'VIP 0'), (1, 'VIP 1'), (2, 'VIP 2'), (3, 'VIP 3'), (4, 'VIP 4'), (5, 'VIP 5'), (6, 'VIP 6')], default=0),
        ),
    ]
