# Generated by Django 6.0.3 on 2026-03-19 19:30

import MyApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_profile_account_name_profile_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(default=MyApp.models.generate_invitation_code, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='withdrawal_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
