# Generated by Django 6.0.3 on 2026-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_profile_bank_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='withdrawal_method',
            field=models.CharField(blank=True, help_text='e.g., Bank Transfer, Tigo Money', max_length=50, null=True),
        ),
    ]
