# Generated by Django 6.0.3 on 2026-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_profile_withdrawal_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='withdrawal_password',
            field=models.CharField(blank=True, help_text='6-digit PIN', max_length=6, null=True),
        ),
    ]
