# Generated by Django 6.0.3 on 2026-03-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_profile_withdrawal_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recharge_qr',
            field=models.ImageField(blank=True, help_text='Upload a unique QR code image for this user', null=True, upload_to='recharge_qrs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recharge_receiver_name',
            field=models.CharField(default='Angel Mishael Rivera Sandoval', help_text='The name shown to this specific user on their recharge page', max_length=100),
        ),
    ]
