# Generated by Django 6.0.3 on 2026-03-20 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_profile_recharge_qr_profile_recharge_receiver_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recharge_qr',
            field=models.ImageField(blank=True, null=True, upload_to='recharge_qrs/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recharge_receiver_name',
            field=models.CharField(default='Angel Mishael Rivera Sandoval', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='withdrawal_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RechargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('screenshot', models.ImageField(upload_to='recharge_proofs/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
