# Generated by Django 6.0.3 on 2026-03-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_withdraw',
            field=models.BooleanField(default=True),
        ),
    ]
