# Generated by Django 6.0.3 on 2026-03-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_profile_referred_by_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('min_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_tasks', models.IntegerField(default=1)),
                ('gradient', models.CharField(default='from-amber-400 to-orange-500', max_length=100)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='vip_level',
            field=models.ForeignKey(blank=True, db_column='vip_level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.viplevel'),
        ),
    ]
