# Generated by Django 6.0.3 on 2026-03-21 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_viplevel_alter_profile_vip_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vip_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='membership_vip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.viplevel'),
        ),
    ]
