# Generated by Django 6.0.3 on 2026-03-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_remove_profile_vip_level_profile_membership_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viplevel',
            name='gradient',
        ),
        migrations.AddField(
            model_name='viplevel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vip_badges/'),
        ),
    ]
