# Generated by Django 6.0.3 on 2026-03-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_remove_viplevel_gradient_viplevel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='withdrawal_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_link', models.URLField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vip_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='MyApp.viplevel')),
            ],
        ),
    ]
