# Generated by Django 6.0.3 on 2026-03-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_alter_profile_withdrawal_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='commission',
        ),
    ]
