# Generated by Django 6.0.3 on 2026-03-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_remove_mission_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='vip_level',
        ),
    ]
