# Generated by Django 6.0.3 on 2026-03-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_remove_mission_vip_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='missions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viplevel',
            name='missions_per_day',
            field=models.IntegerField(default=12),
        ),
    ]
