# Generated by Django 6.0.3 on 2026-03-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_missionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionrecord',
            name='image_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
