# Generated by Django 6.0.3 on 2026-03-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_missionrecord_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionrecord',
            name='scheduled_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pendiente'), ('Completed', 'Completado'), ('Scheduled', 'Programado (Trap)')], default='Completed', max_length=20),
        ),
    ]
