# Generated by Django 6.0.3 on 2026-03-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_missionrecord_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='required_recharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
