# Generated by Django 6.0.3 on 2026-03-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0023_profile_required_recharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='required_recharge',
        ),
        migrations.AddField(
            model_name='missionrecord',
            name='required_recharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
