# Generated by Django 6.0.3 on 2026-03-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0024_remove_profile_required_recharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_system_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='system_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
