# Generated by Django 6.0.4 on 2026-04-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0026_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='order_count',
            field=models.IntegerField(default=1, help_text='Number of orders contained in this mission'),
        ),
        migrations.AddField(
            model_name='missionrecord',
            name='order_count',
            field=models.IntegerField(default=1),
        ),
    ]
