# Generated by Django 6.0.4 on 2026-04-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0027_mission_order_count_missionrecord_order_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ubuy Project', max_length=100)),
                ('global_recharge_receiver_name', models.CharField(default='Angel', max_length=100)),
                ('global_recharge_qr', models.ImageField(blank=True, null=True, upload_to='recharge_qrs/global/')),
                ('is_maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
