# Generated by Django 6.0.4 on 2026-04-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0028_globalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='global_recharge_receiver_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recharge_receiver_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
