# Generated by Django 6.0.4 on 2026-04-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0029_alter_globalsettings_global_recharge_receiver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price of each individual order', max_digits=12),
        ),
        migrations.AddField(
            model_name='missionrecord',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
