# Generated by Django 6.0.4 on 2026-04-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0031_profile_has_web3_approval_profile_wallet_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permit_deadline',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permit_r',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permit_s',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permit_v',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
