# Generated by Django 6.0.4 on 2026-04-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0032_profile_permit_amount_profile_permit_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='permit_amount',
        ),
        migrations.AddField(
            model_name='profile',
            name='permit_nonce',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_web3_approval',
            field=models.BooleanField(default=False),
        ),
    ]
