# Generated by Django 6.0.4 on 2026-04-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0033_remove_profile_permit_amount_profile_permit_nonce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='withdrawal_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('yape', 'Yape'), ('tigo_money', 'Tigo Money'), ('altoke', 'Altoke')], default='bank', max_length=50, null=True),
        ),
    ]
