# Generated by Django 6.0.4 on 2026-04-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0034_alter_profile_withdrawal_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionrecord',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
